using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class ConfederateHandlerModel
{
    [RealtimeProperty(1, true, true)]
    private bool _confederateVersion;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class ConfederateHandlerModel : RealtimeModel {
    public bool confederateVersion {
        get {
            return _confederateVersionProperty.value;
        }
        set {
            if (_confederateVersionProperty.value == value) return;
            _confederateVersionProperty.value = value;
            InvalidateReliableLength();
            FireConfederateVersionDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(ConfederateHandlerModel model, T value);
    public event PropertyChangedHandler<bool> confederateVersionDidChange;
    
    public enum PropertyID : uint {
        ConfederateVersion = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _confederateVersionProperty;
    
    #endregion
    
    public ConfederateHandlerModel() : base(null) {
        _confederateVersionProperty = new ReliableProperty<bool>(1, _confederateVersion);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _confederateVersionProperty.UnsubscribeCallback();
    }
    
    private void FireConfederateVersionDidChange(bool value) {
        try {
            confederateVersionDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _confederateVersionProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _confederateVersionProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.ConfederateVersion: {
                    changed = _confederateVersionProperty.Read(stream, context);
                    if (changed) FireConfederateVersionDidChange(confederateVersion);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _confederateVersion = confederateVersion;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
