using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class GuideRoleModel
{
    [RealtimeProperty(1, true, true)]
    private int _role;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class GuideRoleModel : RealtimeModel {
    public int role {
        get {
            return _roleProperty.value;
        }
        set {
            if (_roleProperty.value == value) return;
            _roleProperty.value = value;
            InvalidateReliableLength();
            FireRoleDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(GuideRoleModel model, T value);
    public event PropertyChangedHandler<int> roleDidChange;
    
    public enum PropertyID : uint {
        Role = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _roleProperty;
    
    #endregion
    
    public GuideRoleModel() : base(null) {
        _roleProperty = new ReliableProperty<int>(1, _role);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _roleProperty.UnsubscribeCallback();
    }
    
    private void FireRoleDidChange(int value) {
        try {
            roleDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _roleProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _roleProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Role: {
                    changed = _roleProperty.Read(stream, context);
                    if (changed) FireRoleDidChange(role);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _role = role;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
