using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel(createMetaModel: true)]
public partial class GuideAudioSyncModel
{
    // The ID of the audio stream on the network
    [RealtimeProperty(1, true, true)]
    private int _streamID = -1;

    // The ID of the user who owns the guide (the Host)
    [RealtimeProperty(2, true, true)]
    private int _clientID = -1;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class GuideAudioSyncModel : RealtimeModel {
    public int streamID {
        get {
            return _streamIDProperty.value;
        }
        set {
            if (_streamIDProperty.value == value) return;
            _streamIDProperty.value = value;
            InvalidateReliableLength();
            FireStreamIDDidChange(value);
        }
    }
    
    public int clientID {
        get {
            return _clientIDProperty.value;
        }
        set {
            if (_clientIDProperty.value == value) return;
            _clientIDProperty.value = value;
            InvalidateReliableLength();
            FireClientIDDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(GuideAudioSyncModel model, T value);
    public event PropertyChangedHandler<int> streamIDDidChange;
    public event PropertyChangedHandler<int> clientIDDidChange;
    
    public enum PropertyID : uint {
        StreamID = 1,
        ClientID = 2,
    }
    
    #region Properties
    
    private ReliableProperty<int> _streamIDProperty;
    
    private ReliableProperty<int> _clientIDProperty;
    
    #endregion
    
    public GuideAudioSyncModel() : base(null) {
        _streamIDProperty = new ReliableProperty<int>(1, _streamID);
        _clientIDProperty = new ReliableProperty<int>(2, _clientID);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _streamIDProperty.UnsubscribeCallback();
        _clientIDProperty.UnsubscribeCallback();
    }
    
    private void FireStreamIDDidChange(int value) {
        try {
            streamIDDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireClientIDDidChange(int value) {
        try {
            clientIDDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _streamIDProperty.WriteLength(context);
        length += _clientIDProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _streamIDProperty.Write(stream, context);
        writes |= _clientIDProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.StreamID: {
                    changed = _streamIDProperty.Read(stream, context);
                    if (changed) FireStreamIDDidChange(streamID);
                    break;
                }
                case (uint) PropertyID.ClientID: {
                    changed = _clientIDProperty.Read(stream, context);
                    if (changed) FireClientIDDidChange(clientID);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _streamID = streamID;
        _clientID = clientID;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
