using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class GuideAudioSyncModel
{
    // 1: Property ID
    // true: Reliable (we need the audio to arrive in order)
    // true: Force change event (fires even if the string is the same)
    [RealtimeProperty(1, true, true)]
    private string _audioChunk;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class GuideAudioSyncModel : RealtimeModel {
    public string audioChunk {
        get {
            return _audioChunkProperty.value;
        }
        set {
            if (_audioChunkProperty.value == value) return;
            _audioChunkProperty.value = value;
            InvalidateReliableLength();
            FireAudioChunkDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(GuideAudioSyncModel model, T value);
    public event PropertyChangedHandler<string> audioChunkDidChange;
    
    public enum PropertyID : uint {
        Result = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _audioChunkProperty;
    
    #endregion
    
    public GuideAudioSyncModel() : base(null) {
        _audioChunkProperty = new ReliableProperty<string>(1, _audioChunk);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _audioChunkProperty.UnsubscribeCallback();
    }
    
    private void FireAudioChunkDidChange(string value) {
        try {
            audioChunkDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _audioChunkProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _audioChunkProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Result: {
                    changed = _audioChunkProperty.Read(stream, context);
                    if (changed) FireAudioChunkDidChange(audioChunk);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _audioChunk = audioChunk;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
