using Normal.Realtime;
using Normal.Realtime.Serialization;
using UnityEngine;

[RealtimeModel]
public partial class GuideAudioSyncModel
{
    [RealtimeProperty(1, true, true)]
    private byte[] _audioClipData;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class GuideAudioSyncModel : RealtimeModel
{
    void Awake()
    {
        Debug.Log("GuideAudioSyncModel is initialized");
    }

    public byte[] audioClipData
    {
        get
        {
            return _audioClipDataProperty.value;
        }
        set
        {
            if (_audioClipDataProperty.value == value) return;
            _audioClipDataProperty.value = value;
            InvalidateReliableLength();
            FireAudioClipDataDidChange(value);
        }
    }

    public delegate void PropertyChangedHandler<in T>(GuideAudioSyncModel model, T value);
    public event PropertyChangedHandler<byte[]> audioClipDataDidChange;

    public enum PropertyID : uint
    {
        AudioClipData = 1,
    }

    #region Properties

    private ReliableProperty<byte[]> _audioClipDataProperty;

    #endregion

    public GuideAudioSyncModel() : base(null)
    {
        _audioClipDataProperty = new ReliableProperty<byte[]>(1, _audioClipData);
        Debug.Log("GuideAudioSyncModel constructor called.");
    }

    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent)
    {
        _audioClipDataProperty.UnsubscribeCallback();
        Debug.Log("OnParentReplaced called.");
    }

    private void FireAudioClipDataDidChange(byte[] value)
    {
        Debug.Log("FireAudioClipDataDidChange called.");
        try
        {
            audioClipDataDidChange?.Invoke(this, value);
            Debug.Log("FireAudioClipDataDidChange try.");
        }
        catch (System.Exception exception)
        {
            UnityEngine.Debug.LogException(exception);
        }
    }

    protected override int WriteLength(StreamContext context)
    {
        var length = 0;
        length += _audioClipDataProperty.WriteLength(context);
        return length;
    }

    protected override void Write(WriteStream stream, StreamContext context)
    {
        Debug.Log("Write called.");
        var writes = false;
        writes |= _audioClipDataProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }

    protected override void Read(ReadStream stream, StreamContext context)
    {
        Debug.Log("Read called.");
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID))
        {
            var changed = false;
            switch (propertyID)
            {
                case (uint)PropertyID.AudioClipData:
                    {
                        changed = _audioClipDataProperty.Read(stream, context);
                        if (changed) FireAudioClipDataDidChange(audioClipData);
                        break;
                    }
                default:
                    {
                        stream.SkipProperty();
                        break;
                    }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged)
        {
            UpdateBackingFields();
        }
    }

    private void UpdateBackingFields()
    {
        Debug.Log("UpdateBackingFields called.");
        _audioClipData = audioClipData;
    }

}
/* ----- End Normal Autogenerated Code ----- */