using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class PlayerType
{
    [RealtimeProperty(1, true, true)]
    private string _name;

    [RealtimeProperty(2, true, true)]
    private string _audioClipName;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class PlayerType : RealtimeModel {
    public string name {
        get {
            return _nameProperty.value;
        }
        set {
            if (_nameProperty.value == value) return;
            _nameProperty.value = value;
            InvalidateReliableLength();
            FireNameDidChange(value);
        }
    }
    
    public string audioClipName {
        get {
            return _audioClipNameProperty.value;
        }
        set {
            if (_audioClipNameProperty.value == value) return;
            _audioClipNameProperty.value = value;
            InvalidateReliableLength();
            FireAudioClipNameDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(PlayerType model, T value);
    public event PropertyChangedHandler<string> nameDidChange;
    public event PropertyChangedHandler<string> audioClipNameDidChange;
    
    public enum PropertyID : uint {
        Name = 1,
        AudioClipName = 2,
    }
    
    #region Properties
    
    private ReliableProperty<string> _nameProperty;
    
    private ReliableProperty<string> _audioClipNameProperty;
    
    #endregion
    
    public PlayerType() : base(null) {
        _nameProperty = new ReliableProperty<string>(1, _name);
        _audioClipNameProperty = new ReliableProperty<string>(2, _audioClipName);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _nameProperty.UnsubscribeCallback();
        _audioClipNameProperty.UnsubscribeCallback();
    }
    
    private void FireNameDidChange(string value) {
        try {
            nameDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireAudioClipNameDidChange(string value) {
        try {
            audioClipNameDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _nameProperty.WriteLength(context);
        length += _audioClipNameProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _nameProperty.Write(stream, context);
        writes |= _audioClipNameProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Name: {
                    changed = _nameProperty.Read(stream, context);
                    if (changed) FireNameDidChange(name);
                    break;
                }
                case (uint) PropertyID.AudioClipName: {
                    changed = _audioClipNameProperty.Read(stream, context);
                    if (changed) FireAudioClipNameDidChange(audioClipName);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _name = name;
        _audioClipName = audioClipName;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
