using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class RoomAttributesModel
{
    [RealtimeProperty(1, true, true)]
    private int _totalPlayers;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class RoomAttributesModel : RealtimeModel {
    public int totalPlayers {
        get {
            return _totalPlayersProperty.value;
        }
        set {
            if (_totalPlayersProperty.value == value) return;
            _totalPlayersProperty.value = value;
            InvalidateReliableLength();
            FireTotalPlayersDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(RoomAttributesModel model, T value);
    public event PropertyChangedHandler<int> totalPlayersDidChange;
    
    public enum PropertyID : uint {
        TotalPlayers = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _totalPlayersProperty;
    
    #endregion
    
    public RoomAttributesModel() : base(null) {
        _totalPlayersProperty = new ReliableProperty<int>(1, _totalPlayers);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _totalPlayersProperty.UnsubscribeCallback();
    }
    
    private void FireTotalPlayersDidChange(int value) {
        try {
            totalPlayersDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _totalPlayersProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _totalPlayersProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.TotalPlayers: {
                    changed = _totalPlayersProperty.Read(stream, context);
                    if (changed) FireTotalPlayersDidChange(totalPlayers);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _totalPlayers = totalPlayers;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
