using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class AudioClipModel
{
    [RealtimeProperty(1, true, true)]
    private string _clipName;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class AudioClipModel : RealtimeModel {
    public string clipName {
        get {
            return _clipNameProperty.value;
        }
        set {
            if (_clipNameProperty.value == value) return;
            _clipNameProperty.value = value;
            InvalidateReliableLength();
            FireClipNameDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(AudioClipModel model, T value);
    public event PropertyChangedHandler<string> clipNameDidChange;
    
    public enum PropertyID : uint {
        ClipName = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _clipNameProperty;
    
    #endregion
    
    public AudioClipModel() : base(null) {
        _clipNameProperty = new ReliableProperty<string>(1, _clipName);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _clipNameProperty.UnsubscribeCallback();
    }
    
    private void FireClipNameDidChange(string value) {
        try {
            clipNameDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _clipNameProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _clipNameProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.ClipName: {
                    changed = _clipNameProperty.Read(stream, context);
                    if (changed) FireClipNameDidChange(clipName);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _clipName = clipName;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
